import {environment} from "../../environments/environment";


const AppConstant = Object.freeze({
    KEY_CURRENT_USER: 'current-user',
    GLOBAL_LOADING: 'GLOBAL-LOADING',
    DEFAULT_URLS: {
        API: `${environment.serverURL}/api`,
    },
    CALENDAR_KO: {
        dateFormat: 'dd/mm/yy',
        firstDay: 1,
        isRTL: false,
        showMonthAfterYear: true,
        yearSuffix: '',
    },
    PATTERNS: {
        EMAIL: /^(([^<>()?\[\]\.,;:\s@\"]+(\.[^<>()?\[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()?[\]\.,;:\s@\"]+\.)+[^<>()?[\]\.,;:\s@\"]{2,})$/,
        USERNAME: /^[a-zA-Z0-9_@.]*$/,
        NO_SP_CHAR: '[^<>{}]*',
        PHONE: /^[0-9-]*$/,
        NUMBER: /^[0-9]*$/,
        POSITIVE_NUMBER: /^[+]?([.]\d+|\d+[.]?\d*)$/,
        ALLOWED_INPUT: /^[0-9a-zA-Z._%+-@]*$/,
        SCRIPT_PATTERN: /^((?!<|>|{|\})[\s\S])*?$/,
        COLOR_PATTERN: /^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/,
        COLOR_RGB_PATTERN: /^RGB\(\s*(?:(\d{1,3})\s*,?){3}\)$/,
        SPECIAL_CHARS_NOT_ALLOW_RENAME:
            /^((?!\\|\/|:|\*|\?|"|<|>|\||\{|})[\s\S])*?$/,
        PASSWORD: /^(?=.*[a-z])(?=.*[0-9]).{8,}$/, // at least 8 characters, including numbers and characters
        URL_PATTERN:
            /^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?/,
    },
    FORMAT_DATE: {
        MOMENT_LONG_DATE: 'MM/DD/YYYY HH:mm:ss',
        MOMENT_SHORT_DATE: 'MM/DD/YYYY',
        DATE_PIPE_LONG_DATE: 'MM/dd/YYYY HH:mm:ss',
        DATE_PIPE_SHORT_DATE: 'MM/dd/YYYY',
        TIME_FORMAT: 'HH:mm:ss',
        SCHEDULE_MEETING_DATE: 'MM/DD/YYYY HH:mm',
        MOMENT_T_DATE: 'yyyy-MM-DDTHH:mm:ss.SSS',
        T_DATE: 'YYYY-MM-DD[T]HH:mm:ss',
        VN_DATE_PIPE_SHORT_DATE: 'DD/MM/YYYY',
    },
    STORAGE_KEYS: {
        SESSION: 'stk',
        LANGUAGE: 'lang',
        USER: 'user',
    },
    ROLE_TYPE: {
        ADMIN: 'ADMIN',
        WRITE: 'WRITE',
        READ_ONLY: 'READ_ONLY',
    },
    USER_ROLE_TYPE: {
        ADMIN: 0,
        WRITE: 1,
        READ_ONLY: 2,
    },
    PRIORITY_PERSON: {
        NguoiKhuyetTat: 0,
        HoNgheoCanNgheo: 1,
        DanTocThieuSo: 2,
    },
    EDUCATION_LEVEL: {
        ChuaXongTieuHoc: 0,
        TotNghiepTieuHoc: 1,
        TotNghiepTHCS: 2,
        TotNghiepTHPT: 3,
    },
    EDUCATION_LEVEL_FOREIGNER: {
        ChungChiDaoTao: 0,
        ThacSi: 1,
        TienSi: 2,
        ChungChiHanhNghe: 3,
    },
    QUALIFICATION: {
        ChuaQuaDaoTao: 0,
        CNKTKHongCoBang: 1,
        Duoi3Thang: 2,
        SoCap: 3,
        TrungCap: 4,
        CaoDang: 5,
        DaiHoc: 6,
        TrenDaiHoc: 7,
    },
    QUALIFICATION_FOREIGNER: {
        KhoaHocGiaoDucVaDaoTaoGiaoVien: 0,
        NhanVan: 1,
        KinhDoanhVaQuanLy: 2,
        KhoaHocSuSongSinhHoc: 3,
        ToanVaThongKe: 4,
        CongNgheKyThuat: 5,
        SanXuatVaCheBien: 6,
        XayDung: 7,
        ThuY: 8,
        DichVuXaHoi: 9,
        DichVuVanTai: 10,
        AnNinhQuocPhong: 11,
        NgheThuat: 12,
        BaoChiVaThongTin: 13,
        PhapLuat: 14,
        KhoaHocTuNhien: 15,
        MayTinhVaCongNgheThongTin: 16,
        KyThuat: 17,
        KienTrucVaXayDung: 18,
        NongLamNghiepVaThuySan: 19,
        SucKhoe: 20,
        DuLichKhachSanTheThaoVaDichVuCaNhan: 21,
        MoiTruongVaBaoVeMoiTruong: 22,
    },
    POSITION: {
        NhaQuanLy: 0,
        GiamDocDieuHanh: 1,
        ChuyenGia: 2,
        LaoDongKyThuat: 3,
    },
    JOB_PROFESSION: {
        NhaChuyenMonKyThuatVienKhoaHocVaKyThuat: 0,
        NhaChuyenMonKyThuatVienVeSucKhoe: 1,
        NhaChuyenMonGiaoVienGiangDay: 2,
        NhaChuyenMonNhanVienVeKinhDoanhVaQuanLy: 3,
        NhaChuyenMonKyThuatTrongLinhVucCongNgheThongTinVaTruyenThong: 4,
        NhaChuyenMonNhanVienVePhapLuatVanHoaXaHoi: 5,
        LaoDongTrongKhaiKhoangXayDungCongNghiepCheBienCheTaoVaGiaoThongVanTai: 6,
        NhânVienTongHopVanPhongVaCacCongViecBanGiay: 7,
        LaoDongKyThuatTrongNongNghiepLamNghiepVaThuySan: 8,
        LaoDongKyThuatTrongXayDungLuyenkimCoKhi: 9,
        ThoDienDienTuCheBienThucPhamGoMayMacDoThuCong: 10,
        ThoLapRapVanHanhMayMocVaThietBi: 11,
    },
    WORKING_FORM: {
        ThucHienHopDongLaoDong: 0,
        DiChuyenTrongNoiBoDoanhNghiep: 1,
        ThucHienCacLoaiHopDongHoacThoaThuan: 2,
        LamViecChoToChucPhiChinhPhuNuocNgoaiToChucQuocTeTaiVietNam: 3,
        NhaQuanLyGiamDocDieuHanhChuyenGiaLaoDongKyThuat: 4,
        ThamGiaThucHienCacGoiThauDuAnTaiVietNam: 5,
    },
    ECONOMIC_ACTIVITY: {
        DiHoc: 0,
        HuuTri: 1,
        NoiTro: 2,
        KhuyetTat: 3,
    },
});

export default AppConstant;

